use_frameworks!

target 'SHDateFormatter_Example' do
  pod 'SHDateFormatter', :path => '../'

  target 'SHDateFormatter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
